import Head from 'next/head';
import React from 'react';
import { useForm } from 'react-hook-form';
import Button from '../components/Button';
import Input from '../components/Input';
import { useAuth } from '../context/AuthContext';

import { parseCookies } from 'nookies';

import styles from '../styles/pages/Login.module.scss';
import { GetServerSidePropsContext } from 'next';

export default function Login() {
  const { register, handleSubmit } = useForm();

  const { signIn } = useAuth();

  const onSubmit = async (data: any) => {
    await signIn(data);
  };
  return (
    <div className={styles.loginContainer}>
      <Head>
        <title>Filmes Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.formContainer}>
        <h2 className={styles.loginText}>Log in</h2>
        <form className={styles.form} onSubmit={handleSubmit(onSubmit)}>
          <Input
            id="email"
            name="email"
            type="text"
            label="Email"
            placeholder=" "
            register={register}
          />
          <Input
            id="password"
            name="password"
            type="password"
            label="Password"
            placeholder=" "
            register={register}
          />

          <Button>Login</Button>
        </form>
      </div>
    </div>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { '@filmesweb.token': token } = parseCookies(context);
  const { '@filmesweb.user': user } = parseCookies(context);

  if (token && user) {
    return {
      redirect: {
        destination: '/',
      },
    };
  }

  return {
    props: {},
  };
}
